pawn_marker:
  ros__parameters:
    shape_type: "SPHERE"
    frame_id: "base_link"
    ns: "marker"
    x: 0.5
    y: 0.5
    z: 0.08
    qx: 0.0
    qy: 0.0
    qz: 0.0
    qw: 1.0
    scale_x: 0.1
    scale_y: 0.1
    scale_z: 0.1
    color_r: 0.0
    color_g: 1.0
    color_b: 0.0
    color_a: 1.0
